---
title: "Cluster Analysis in R"
output: html_document
---

#### Install libraries

```{r install-libraries, message=FALSE}
library(tidyverse) # Organising data
library(dplyr)
library(corrplot) # Plotting data
library(ggplot2) 
library(sf) # Working with spatial data
library(tmap)
library(cluster) # Cluster analysis
library(factoextra) 
library(gridExtra)
library(RColorBrewer) # Colour palettes
```

#### Download the data

```{r download data, message=FALSE}
gl_efficiency <- st_read("greaterlondon_efficiency.gpkg")
```

#### List the variables

```
colnames(gl_efficiency)
```

#### Map the variables

```{r map-variables}
tm_shape(gl_efficiency)+
  tm_fill(col = "rating_current_Dandbelow", 
          title = "Properties",
          palette = "RdYlBu")+
  tm_layout(frame = FALSE)
```

#### Standardise the variables

```{r standardise-data, message = FALSE}
gl_efficiency_df <- st_drop_geometry(gl_efficiency)
gl_efficiency_df <- scale(gl_efficiency_df)
```

#### Explore relationships between variables

```{r correlation}
# Rename columns for the plot
colnames(gl_efficiency_df) <- c("Private rental properties", 
                                "Built pre-1900", 
                                "Built since 2021", 
                                "Current rating D and below", 
                                "Potential rating D and below", 
                                "Terrace", 
                                "House or bungalow", 
                                "Flat or maisonette", 
                                "Inefficient hot water", 
                                "Inefficient walls", 
                                "Inefficient mains heating")

# Calculate correlation
corr = cor(gl_efficiency_df, method = "pearson")
```

```{r corr-plot}
# Plot correlation matrix
corrplot(corr = corr,
         method = "circle",
         type = "upper",
         order = "alphabet",
         tl.col = "black", # Labels set as black
         sig.level = 0.05) 
```

```{r wss-plot}
set.seed(125) # Set initial seed
fviz_nbclust(gl_efficiency_df, kmeans, method = "wss") # Compute total within-cluster sum of square
```

#### Generate k-means solutions

```{r kmeans-clustering}
# Generate clusters for 5, 6 and 7 clusters
kmeans_5 <- kmeans(gl_efficiency_df, 
                   centers = 5, 
                   iter.max = 1000)

kmeans_6 <- kmeans(gl_efficiency_df, 
                   centers = 6, 
                   iter.max = 1000)

kmeans_7 <- kmeans(gl_efficiency_df, 
                   centers = 7, 
                   iter.max = 1000)
```

```{r kmeans-size}
kmeans_5$size
kmeans_6$size
kmeans_7$size
```

#### Visualise cluster centres

```{r heat-map-cluster-center}
# Define the center of each cluster
cluster <- c(1: 6)
center <- kmeans_6$centers
center_df <- data.frame(cluster, center)

# Reshape the data into a long format
center_reshape <- gather(center_df, features, values, Private.rental.properties:Inefficient.mains.heating)

# Edit the labels                         
center_reshape <- center_reshape %>%
    mutate(features = recode(features, 
                             "Private.rental.properties" = "Private rental properties",
                            "Built.pre.1900" = "Built pre 1900",
                            "Built.since.2021" = "Built since 2021",
                            "Current.rating.D.and.below" = "Current rating D or below",
                            "Potential.rating.D.and.below" = "Potential rating D or below",
                            "Terrace" = "Terrace",
                            "House.or.bungalow" = "House or bungalow",
                            "Flat.or.maisonette" = "Flat or maisonette",
                            "Inefficient.hot.water" = "Inefficienct hot water",
                            "Inefficient.walls" = "Inefficient walls",
                            "Inefficient.mains.heating" = "Inefficienct mains heating"))

# Specify the colour palette
hm.palette <-colorRampPalette(brewer.pal(9, 'Blues'), space='Lab')

# Plot the centers for each variable
ggplot(data = center_reshape, aes(x = features, y = cluster, fill = values)) +
    scale_y_continuous(breaks = seq(1, 14, by = 1)) +
    geom_tile() +
    coord_equal() +
    scale_fill_gradientn(colours = hm.palette(90)) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

#### Map final clusters

```{r cluster-data-output}
# Add cluster information to original data
gl_efficiency_clusters <- gl_efficiency

gl_efficiency_clusters$cluster_5 <- as.character(kmeans_5$cluster)
gl_efficiency_clusters$cluster_6 <- as.character(kmeans_6$cluster)
gl_efficiency_clusters$cluster_7 <- as.character(kmeans_7$cluster)

# Convert back to sf format
gl_efficiency_clusters_sf <- st_as_sf(gl_efficiency_clusters)
```

```{r map-clusters}
tm_shape(gl_efficiency_clusters_sf)+
  tm_fill("cluster_6", 
          title = "Cluster",
          palette = c( "1" = "#11467b",
      "2" = "#ffd14d", 
      "3" = "#14909a",
      "4" = "#7fbee9",
      "5" = "#df5454",
      "6" = "#7b1072"))+
  tm_layout(frame = FALSE)
```
